# Generated by Django 4.2.1 on 2023-06-14 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='bidding',
            new_name='Bids',
        ),
    ]
