# Generated by Django 4.2.1 on 2023-07-04 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0005_alter_vote_survey'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='question',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vote',
            name='survey',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='polly.survey'),
        ),
    ]
