# Generated by Django 4.2.1 on 2023-07-04 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0006_vote_question_alter_vote_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vote',
            name='survey',
        ),
    ]
