# Generated by Django 4.2.1 on 2023-07-05 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polly', '0007_remove_vote_survey'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('survey', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='survey', to='polly.survey')),
                ('vote', models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='vote', to='polly.vote')),
            ],
        ),
    ]
